options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _PROJECT_ID: "studio-9381016045-4d625"
  _REGION: "us-central1"
  _ARTIFACT_REGISTRY_LOCATION: "us-central1"
  _ARTIFACT_REGISTRY_REPO: "artifact-repo"
  _DUCKDB_IMAGE_NAME: "duckdb-analytics"
  _DUCKDB_SA: "financewise-app-ser@studio-9381016045-4d625.iam.gserviceaccount.com"
  _INGEST_SA: "ingestion-sa@studio-9381016045-4d625.iam.gserviceaccount.com"
  _TRANSFORM_SA: "transformation-sa@studio-9381016045-4d625.iam.gserviceaccount.com"
  _ACCOUNTING_SA: "accounting-sa@studio-9381016045-4d625.iam.gserviceaccount.com"
  _FUNCTION_REGION: "us-central1"
timeout: "1200s"
steps:
# 1. Frontend: install & build
- name: 'gcr.io/cloud-builders/npm'
  id: 'install-frontend-deps'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cd frontend
      npm ci

- name: 'gcr.io/cloud-builders/npm'
  id: 'build-frontend'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cd frontend
      npm run build

# 2. Build DuckDB analytics Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-build-duckdb'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      IMAGE="${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_DUCKDB_IMAGE_NAME}:latest"
      echo "Building image ${IMAGE}"
      docker build -t "${IMAGE}" services/duckdb-analytics
      docker push "${IMAGE}"
  timeout: '1200s'

# 3. Deploy DuckDB image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'deploy-cloud-run-duckdb'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      IMAGE="${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_DUCKDB_IMAGE_NAME}:latest"
      gcloud run deploy duckdb-analytics \
        --image="${IMAGE}" \
        --region="${_REGION}" \
        --platform=managed \
        --service-account="${_DUCKDB_SA}" \
        --no-allow-unauthenticated \
        --set-env-vars=PROJECT_ID="${_PROJECT_ID}" \
        --project="${_PROJECT_ID}"

# 4. Deploy Ingestion Cloud Function (HTTPS)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'deploy-ingest-function'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud functions deploy ingest_data \
        --region=${_FUNCTION_REGION} \
        --runtime=python311 \
        --trigger-http \
        --service-account=${_INGEST_SA} \
        --entry-point=ingest_data \
        --memory=1GB \
        --timeout=300s \
        --source=functions/8-data-ingestion \
        --set-env-vars=RAW_ROWS_TOPIC=raw-rows-created,PROJECT_ID=${_PROJECT_ID} \
        --project=${_PROJECT_ID}

# 5. Sync Shared and Deploy Mapping Engine (Pub/Sub: raw-rows-created)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'sync-shared-to-transform'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cp -r shared/ functions/2-transformation/
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'deploy-transform-function'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud pubsub topics create raw-rows-created --project=${_PROJECT_ID} || true
      gcloud functions deploy transform_raw_rows \
        --region=${_FUNCTION_REGION} \
        --runtime=python311 \
        --trigger-topic=raw-rows-created \
        --service-account=${_TRANSFORM_SA} \
        --entry-point=transform_raw_rows \
        --memory=512MB \
        --timeout=300s \
        --source=functions/2-transformation \
        --set-env-vars=NORMALIZED_ROWS_TOPIC=normalized-rows-created,PROJECT_ID=${_PROJECT_ID} \
        --project=${_PROJECT_ID}

# 6. Deploy Accounting Engine (Pub/Sub: normalized-rows-created)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'deploy-accounting-function'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud pubsub topics create normalized-rows-created --project=${_PROJECT_ID} || true
      gcloud functions deploy accounting_handler \
        --region=${_FUNCTION_REGION} \
        --runtime=python311 \
        --trigger-topic=normalized-rows-created \
        --service-account=${_ACCOUNTING_SA} \
        --entry-point=accounting_handler \
        --memory=512MB \
        --timeout=300s \
        --source=functions/6-accounting-engine \
        --set-env-vars=PROJECT_ID=${_PROJECT_ID} \
        --project=${_PROJECT_ID}

images:
  - "${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_DUCKDB_IMAGE_NAME}:latest"
