
steps:
# 1. Deploy the Data Transformation Function (GCS Trigger)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'gcloud'
  - 'functions'
  - 'deploy'
  - 'data-transformation'
  - '--source=./functions/data_transformation'
  - '--runtime=python39'
  - '--trigger-resource=gs://raw-financial-data-ingestion'
  - '--trigger-event=google.storage.object.finalize'
  - '--entry-point=transform_and_load_data'
  - '--region=us-central1'
  - '--project=$PROJECT_ID'
  - '--service-account=firebase-service-account@$PROJECT_ID.iam.gserviceaccount.com'

# 2. Deploy the Variance Calculation Function (Firestore Trigger)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'gcloud'
  - 'functions'
  - 'deploy'
  - 'calculate-variance'
  - '--source=./functions/calculate_variance'
  - '--runtime=python39'
  - '--trigger-event=providers/cloud.firestore/eventTypes/document.create'
  - '--trigger-resource=projects/$PROJECT_ID/databases/(default)/documents/july_sgg_transactions/{transactionId}'
  - '--entry-point=calculate_variance'
  - '--region=us-central1'
  - '--project=$PROJECT_ID'
  - '--service-account=firebase-service-account@$PROJECT_ID.iam.gserviceaccount.com'

# 3. Build the container for the Financial Analysis Engine
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/financial-analysis-engine', './financial-analysis-engine']

# 4. Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/financial-analysis-engine']

# 5. Deploy the Financial Analysis Engine to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'gcloud'
  - 'run'
  - 'deploy'
  - 'financial-analysis-engine'
  - '--image=gcr.io/$PROJECT_ID/financial-analysis-engine'
  - '--platform=managed'
  - '--region=us-central1'
  - '--allow-unauthenticated'
  - '--project=$PROJECT_ID'
  - '--set-env-vars=VERTEX_AI_ENDPOINT=YOUR_VERTEX_AI_ENDPOINT_HERE' # IMPORTANT: Replace with your actual endpoint ID
  - '--service-account=firebase-service-account@$PROJECT_ID.iam.gserviceaccount.com'

images:
- 'gcr.io/$PROJECT_ID/financial-analysis-engine'
