steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/financial-analysis-engine:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/financial-analysis-engine:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/financial-analysis-engine:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/financial-analysis-engine:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'financial-analysis-engine'
      - '--image'
      - 'gcr.io/$PROJECT_ID/financial-analysis-engine:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID,ARTIFACT_BUCKET=$PROJECT_ID-ml-artifacts'

images:
  - 'gcr.io/$PROJECT_ID/financial-analysis-engine:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/financial-analysis-engine:latest'

options:
  logging: CLOUD_LOGGING_ONLY
