import functions_framework
import json  # lightweight
# Heavy imports moved inside function


# This function should be an HTTP function (callable from frontend)
@functions_framework.http
def run_financial_simulation(request):
    """
    HTTP Cloud Function to run Financial Prognostics using Prophet.
    Accepts: { horizon, inflation, seasonality, etc. }
    Returns: JSON with forecast data and explanation.
    """
    
    # helper for CORS
    if request.method == 'OPTIONS':
        headers = {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'POST',
            'Access-Control-Allow-Headers': 'Content-Type',
            'Access-Control-Max-Age': '3600'
        }
        return ('', 204, headers)

    headers = { 'Access-Control-Allow-Origin': '*' }

    try:
        request_json = request.get_json(silent=True)
        
        # Default Parameters
        horizon = 12
        inflation = 2.0
        seasonality = True
        
        if request_json:
            horizon = request_json.get('horizon', 12)
            inflation = request_json.get('inflation', 2.0)
            seasonality = request_json.get('seasonality', True)

        print(f"[ANALYSIS] Running simulation: Horizon={horizon}, Inflation={inflation}%, Seasonality={seasonality}")

        # Lazy Imports
        import pandas as pd
        import numpy as np
        from prophet import Prophet
        from google.cloud import storage

        # --- DATA LOADING (Mocking read from Storage for now, assuming files exist) ---
        # In a real scenario, we would read:
        # uri = "gs://raw-financial-data-ingestion/Actual PY.txt"
        # df = pd.read_csv(uri)
        
        # Generating Synthetic "Actuals" Data to feed the model
        # (This replaces the mock in the frontend, but still generates data here 
        # because we don't have the physical files in this environment yet)
        dates = pd.date_range(start='2021-01-01', end='2023-12-31', freq='M')
        base_val = 50000
        
        df_data = []
        for i, date in enumerate(dates):
            val = base_val + (i * 200) + (np.random.normal(0, 1000))
            # Inject Seasonality logic if it was "historical" data
            if date.month in [10, 11, 12]:
                val += 5000
            
            df_data.append({'ds': date, 'y': val})
            
        df = pd.DataFrame(df_data)

        # --- PROPHET MODELING ---
        # Initialize Prophet
        m = Prophet(yearly_seasonality=seasonality, weekly_seasonality=False, daily_seasonality=False)
        
        # Add Regressors/Drivers based on params? 
        # For simplicity, we stick to univariate time series with inflation trend adjustment
        
        m.fit(df)

        # Create Future Dataframe
        future = m.make_future_dataframe(periods=horizon, freq='M')
        
        # Forecast
        forecast = m.predict(future)

        # --- ADJUSTMENTS & POST-PROCESSING ---
        # Apply "Inflation" lever manually to the forecast trend
        # (Prophet handles trend, but we want to user-override it)
        
        forecast_tail = forecast.tail(horizon).copy()
        
        # Apply inflation compound to the predicted 'yhat'
        inflation_multiplier = 1 + (inflation / 100)
        
        # We apply strictly to the future part
        # Logic: Enhance the trend component by the inflation factor
        
        results = []
        
        # Combine Historical + Forecast
        # output format compatible with Recharts (month string, actual, forecast, bounds)
        
        # 1. Historicals
        for idx, row in df.iterrows():
            results.append({
                "month": row['ds'].strftime('%Y-%b'),
                "actual": round(row['y'], 2),
                "forecast": None,
                "lower": None,
                "upper": None
            })
            
        # 2. Forecast
        for idx, row in forecast_tail.iterrows():
            # Apply user inflation knob
            adjusted_yhat = row['yhat'] * inflation_multiplier
            uncertainty = (row['yhat_upper'] - row['yhat_lower']) / 2
            
            # Widen uncertainty if inflation is high
            if inflation > 5:
                uncertainty *= 1.5
                
            results.append({
                "month": row['ds'].strftime('%Y-%b'),
                "actual": None,
                "forecast": round(adjusted_yhat, 2),
                "lower": round(adjusted_yhat - uncertainty, 2),
                "upper": round(adjusted_yhat + uncertainty, 2)
            })

        # --- EXPLANATION GENERATION ---
        explanation = f"Generated by backend Prophet Engine. "
        explanation += f"Trained on {len(df)} historical data points. "
        if seasonality:
            explanation += "Seasonality enabled (Q4 weight). "
        if inflation > 5:
            explanation += f"Inflation adjustment (+{inflation}%) applied to trend. "
            
        response_data = {
            "chartData": results,
            "explanation": explanation
        }

        return (json.dumps(response_data), 200, headers)

    except Exception as e:
        print(f"[ANALYSIS-ERROR] {e}")
        return (json.dumps({"error": str(e)}), 500, headers)
