from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from io import BytesIO

class PDFGenerator:
    def generate_pdf_summary(self, month: str) -> BytesIO:
        """
        Generates a standard summary report.
        """
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)
        c.drawString(100, 750, f"SGP Financial Report - {month}")
        c.drawString(100, 730, "Generated by Financial Intelligence Engine")
        c.save()
        buffer.seek(0)
        return buffer

    def generate_executive_scorecard(self, metrics: dict) -> BytesIO:
        """
        Generates a 1-page Executive Scorecard.
        """
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)

        # Header
        c.setFont("Helvetica-Bold", 20)
        c.drawString(50, 800, "SGP EXECUTIVE SCORECARD")
        c.setFont("Helvetica", 12)
        c.drawString(50, 780, f"Reporting Period: January 2025") # Dynamic in real app

        # 1. Financial Performance
        c.setStrokeColorRGB(0, 0, 0)
        c.rect(50, 650, 500, 100)
        c.setFont("Helvetica-Bold", 14)
        c.drawString(60, 720, f"Actual Net Revenue: {metrics.get('net_revenue', 0):,.0f} GEL")
        c.drawString(60, 700, f"Actual Gross Margin: {metrics.get('gross_margin', 0):,.0f} GEL")

        # 2. AI Forecast (Predictive)
        c.setFont("Helvetica", 12)
        c.drawString(60, 620, "NEXT MONTH OUTLOOK (AI.FORECAST):")
        c.setFont("Helvetica-Bold", 14)
        c.drawString(60, 600, f"Predicted Margin: {metrics.get('forecast_margin', 0):,.0f} GEL")

        # 3. Breakeven Threshold
        c.setFont("Helvetica", 12)
        c.drawString(60, 550, f"Breakeven Margin Required: {metrics.get('breakeven', 0.05):,.2f} GEL per unit")

        # Status Alert
        # Logic: If gross_margin < breakeven total (unit * vol). Simplified check here.
        # Assuming metrics pass 'is_critical' boolean or we calc on fly.
        if metrics.get('is_critical', False):
            c.setFillColorRGB(0.8, 0, 0) # Red
            c.setFont("Helvetica-Bold", 12)
            c.drawString(60, 500, "CRITICAL: CURRENT MARGIN BELOW BREAKEVEN")

        c.save()
        buffer.seek(0)
        return buffer

pdf_generator = PDFGenerator()
