from firebase_functions import https_fn, options
import logging
import json

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

@https_fn.on_request(
    cors=options.CorsOptions(cors_origins="*", cors_methods=["POST", "OPTIONS"]),
    timeout_sec=60,
    memory=options.MemoryOption.MB_256,
)
def generate_executive_report(req: https_fn.Request) -> https_fn.Response:
    """
    Lightweight Executive Report Generator.
    Input: {"quarter": "Q3", "data_summary": {...}, "format": "html"}
    Output: HTML String (converted from Markdown)
    """
    try:
        import markdown
        
        req_json = req.get_json(silent=True) or {}
        financial_data = req_json.get("data_summary", {})
        output_format = req_json.get("format", "html") # 'html' or 'text'
        quarter = req_json.get("quarter", "Current Quarter")
        
        # 1. Generate Narrative (Template-based for MVP speed)
        metrics = financial_data.get('metrics', {})
        revenue = metrics.get('revenue', 0)
        net_income = metrics.get('net_income', 0)
        ebitda = metrics.get('ebitda', 0)
        
        narrative_md = f"""# Executive Financial Report - {quarter}

## Executive Summary
For the period of **{quarter}**, the company reported total revenue of **₾{revenue:,.2f}**. Net income stood at **₾{net_income:,.2f}**, reflecting a verified financial position.

## Key Performance Indicators
| Metric | Value |
| :--- | :--- |
| **Revenue** | ₾{revenue:,.2f} |
| **Net Income** | ₾{net_income:,.2f} |
| **EBITDA** | ₾{ebitda:,.2f} |

## Strategic Assessment
Review of current metrics indicates {'stable' if net_income > 0 else 'challenging'} performance. Recommended actions focus on optimizing operational efficiency and revenue growth channels.

---
*Generated by FinanceWise Intelligence*
"""

        # 2. Output Handling
        if output_format == 'text':
             return https_fn.Response(json.dumps({"report_text": narrative_md}), status=200, headers={"Content-Type": "application/json"})
            
        # Convert to HTML
        html_content = markdown.markdown(narrative_md, extensions=['tables'])
        
        # Wrap in professional CSS
        final_html = f"""
        <html>
        <head>
            <style>
                body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; max-width: 800px; margin: auto; padding: 40px; color: #333; line-height: 1.6; }}
                h1 {{ color: #004085; border-bottom: 2px solid #004085; padding-bottom: 10px; }}
                h2 {{ color: #0056b3; margin-top: 30px; }}
                table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
                th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #e0e0e0; }}
                th {{ background-color: #f8f9fa; font-weight: 600; color: #495057; }}
                hr {{ border: 0; border-top: 1px solid #eee; margin: 40px 0; }}
                small {{ color: #6c757d; }}
            </style>
        </head>
        <body>
            {html_content}
        </body>
        </html>
        """
        
        return https_fn.Response(json.dumps({"report_html": final_html}), status=200, headers={"Content-Type": "application/json"})

    except Exception as e:
        logger.error(f"Report Generation Error: {e}")
        return https_fn.Response(json.dumps({"error": str(e)}), status=500, headers={"Content-Type": "application/json"})
