import functions_framework
import vertexai
from vertexai.generative_models import GenerativeModel
import markdown

vertexai.init(location="us-central1")
model = GenerativeModel("gemini-1.5-pro-001")

@functions_framework.http
def generate_executive_report(request):
    """
    Input: {"quarter": "Q3", "data_summary": {...}}
    Output: HTML String
    """
    req = request.get_json(silent=True) or {}
    financial_data = req.get("data_summary", {})
    
    # 1. The Analyst Prompt
    prompt = f"""
    Act as a CFO. Write a quarterly report based on this data:
    {financial_data}

    Structure:
    # Executive Summary
    ## Key Performance Indicators
    ## Risk Analysis (Identify anomalies)
    ## Strategic Recommendations

    Tone: Professional, Concise.
    Format: Markdown.
    """
    
    # 2. Generate Content
    response = model.generate_content(prompt)
    
    # 3. Convert to Report
    html_content = markdown.markdown(response.text)
    
    # Wrap in nice CSS
    final_html = f"""
    <html>
    <body style="font-family: sans-serif; max-width: 800px; margin: auto; padding: 20px;">
        {html_content}
        <hr>
        <small>Generated by Vertex AI Financial Engine</small>
    </body>
    </html>
    """
    
    return {"report_html": final_html}
